# Generated by Django 5.2.7 on 2026-06-28 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "logger_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("message", models.TextField()),
                (
                    "exception_type",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("exception_traceback", models.TextField(blank=True, default="")),
                ("url", models.CharField(blank=True, default="", max_length=500)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("query_string", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "user_display",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
