# Generated by Django 5.2.7 on 2026-06-13 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "counter_type",
                    models.CharField(
                        choices=[
                            ("Main Restaurant LSR", "Main Restaurant LSR"),
                            ("Adventure Area", "Adventure Area"),
                            ("Reception", "Reception"),
                            ("Water Sports", "Water Sports"),
                            ("Water Sport Tuck Shop", "Water Sport Tuck Shop"),
                            ("Event Bar", "Event Bar"),
                            ("Shooting Range", "Shooting Range"),
                            ("Tuck Shop (Main)", "Tuck Shop (Main)"),
                            ("Night Stay", "Night Stay"),
                            ("Group/Event", "Group/Event"),
                            ("Auction", "Auction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("IBFT", "IBFT"),
                            ("Credit Card", "Credit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "POS entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
