# Generated by Django 5.2.7 on 2026-06-30 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('no_of_tickets', models.PositiveIntegerField(default=1)),
                ('rate_per_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(choices=[('Weather Cancellation', 'Weather Cancellation'), ('Restaurant 6% Tax Paid Online', 'Restaurant 6% Tax Paid Online'), ('Other', 'Other')], default='Weather Cancellation', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Ticket Refunds',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
