# Generated by Django 5.2.7 on 2026-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_counters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrycounterform",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrycounterform",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entrycounterform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="entrytransaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrytransaction",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entrytransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
