# Generated by Django 5.2.7 on 2026-06-13 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_counters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entrycounterform",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrycounterform",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entrycounterform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="entrytransaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrytransaction",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entrytransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CashHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "counter_type",
                    models.CharField(
                        choices=[
                            ("Main Restaurant LSR", "Main Restaurant LSR"),
                            ("Adventure Area", "Adventure Area"),
                            ("Reception", "Reception"),
                            ("Water Sports", "Water Sports"),
                            ("Water Sport Tuck Shop", "Water Sport Tuck Shop"),
                            ("Event Bar", "Event Bar"),
                            ("Shooting Range", "Shooting Range"),
                            ("Tuck Shop (Main)", "Tuck Shop (Main)"),
                            ("Night Stay", "Night Stay"),
                            ("Group/Event", "Group/Event"),
                            ("Auction", "Auction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cash_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "counter_type",
                    models.CharField(
                        choices=[
                            ("Main Restaurant LSR", "Main Restaurant LSR"),
                            ("Adventure Area", "Adventure Area"),
                            ("Reception", "Reception"),
                            ("Water Sports", "Water Sports"),
                            ("Water Sport Tuck Shop", "Water Sport Tuck Shop"),
                            ("Event Bar", "Event Bar"),
                            ("Shooting Range", "Shooting Range"),
                            ("Tuck Shop (Main)", "Tuck Shop (Main)"),
                            ("Night Stay", "Night Stay"),
                            ("Group/Event", "Group/Event"),
                            ("Auction", "Auction"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "on_duty_cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_register_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_register_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cash Register entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
