# Generated by Django 5.2.7 on 2026-06-11 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_counters', '0002_entrycounterform_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('counter_type', models.CharField(choices=[('Main Restaurant LSR', 'Main Restaurant LSR'), ('Adventure Area', 'Adventure Area'), ('Reception', 'Reception'), ('Water Sports', 'Water Sports'), ('Water Sport Tuck Shop', 'Water Sport Tuck Shop'), ('Event Bar', 'Event Bar'), ('Shooting Range', 'Shooting Range'), ('Tuck Shop (Main)', 'Tuck Shop (Main)'), ('Night Stay', 'Night Stay'), ('Group/Event', 'Group/Event')], max_length=50)),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_handovers', to=settings.AUTH_USER_MODEL)),
                ('handover_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_handovers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
