# Generated by Django 5.2.7 on 2026-06-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_counters', '0003_cashhandover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashhandover',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cashhandover',
            name='date',
        ),
    ]
