# Generated by Django 5.2.7 on 2026-06-11 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_counters', '0004_alter_cashhandover_options_remove_cashhandover_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashhandover',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
