# Generated by Django 5.2.7 on 2026-06-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_counters', '0006_alter_cashhandover_counter_type_cashregister'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='received_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
