# Generated by Django 5.2.7 on 2026-06-13 15:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("jetski", "Jetski"),
                            ("boat", "Boat"),
                            ("speedboat", "Speed Boat"),
                            ("parasail", "Parasailing Boat"),
                            ("vehicle", "Vehicle"),
                            ("equipment", "Equipment"),
                            ("fuel", "Fuel"),
                            ("ammo", "Ammo"),
                            ("generator", "Generator"),
                            ("ambulance", "Ambulance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("supplier", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fuel_used_liters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_generator_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generator_logs",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FuelTransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("pending", "Pending"),
                            ("required", "Required"),
                            ("purchased", "Purchased"),
                            ("issued", "Issued"),
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fuel_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_txns",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "issued_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_received_logs",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fuel Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AmmoTransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "bullet_type",
                    models.CharField(
                        choices=[
                            ("9mm", "9mm"),
                            (".45", ".45"),
                            (".22", ".22"),
                            (".38", ".38"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("pending", "Pending"),
                            ("required", "Required"),
                            ("purchased", "Purchased"),
                            ("issued", "Issued"),
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bullet_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("paid_via_tickets", "Paid via Tickets"),
                            ("paid_via_groups", "Paid via Groups"),
                            ("free", "Free Bullets"),
                        ],
                        max_length=20,
                    ),
                ),
                ("free_bullet_reason", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ammo_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ammo_txns",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ammo Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AmbulanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("patient_name", models.CharField(default="", max_length=150)),
                (
                    "patient_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("guest", "Guest"),
                            ("local", "Local"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "start_reading_km",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "end_reading_km",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "medical_expense",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        choices=[
                            ("khanpur", "Khanpur (Local)"),
                            ("haripur", "Haripur"),
                            ("taxila", "Taxila"),
                            ("pof", "POF Hospital"),
                            ("rawalpindi_isb", "Rawalpindi/Islamabad"),
                            ("abbottabad", "Abbottabad"),
                            ("others", "Others"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambulance_drives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ambulance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambulance_logs",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ambulance Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
