# Generated by Django 5.2.7 on 2026-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ammotransactionlog",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("required", "Required"),
                    ("purchased", "Purchased"),
                    ("cancelled", "Cancelled"),
                    ("issued", "Issued"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fueltransactionlog",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("required", "Required"),
                    ("purchased", "Purchased"),
                    ("cancelled", "Cancelled"),
                    ("issued", "Issued"),
                ],
                max_length=20,
            ),
        ),
    ]
