# Generated by Django 5.2.7 on 2026-06-12 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulancelog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Ambulance Logs'},
        ),
        migrations.AddField(
            model_name='ambulancelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ambulancelog',
            name='patient_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ambulancelog',
            name='patient_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('guest', 'Guest'), ('local', 'Local')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulancelog',
            name='hospital',
            field=models.CharField(choices=[('khanpur', 'Khanpur (Local)'), ('haripur', 'Haripur'), ('taxila', 'Taxila'), ('pof', 'POF Hospital'), ('rawalpindi_isb', 'Rawalpindi/Islamabad'), ('abbottabad', 'Abbottabad'), ('others', 'Others')], max_length=30),
        ),
    ]
