# Generated by Django 5.2.7 on 2026-06-12 19:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ambulancelog_options_ambulancelog_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('engine_oil', 'Engine Oil')], max_length=20)),
                ('status', models.CharField(choices=[('purchased', 'Purchased'), ('issued', 'Issued')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('issued_to', models.CharField(blank=True, choices=[('J1', 'J1 (Jetski)'), ('J2', 'J2 (Jetski)'), ('J3', 'J3 (Jetski)'), ('J4', 'J4 (Jetski)'), ('J5', 'J5 (Jetski)'), ('J6', 'J6 (Jetski)'), ('J7', 'J7 (Jetski)'), ('J8', 'J8 (Jetski)'), ('J9', 'J9 (Jetski)'), ('J10', 'J10 (Jetski)'), ('J11', 'J11 (Jetski)'), ('B1', 'B1 (Boat)'), ('B2', 'B2 (Boat)'), ('B3', 'B3 (Boat)'), ('B4', 'B4 (Boat)'), ('B5', 'B5 (Boat)'), ('SP1', 'SP1 (Speed Boat)'), ('SP2', 'SP2 (Speed Boat)'), ('SP3', 'SP3 (Speed Boat)'), ('P1', 'P1 (Parasailing Boat)'), ('P2', 'P2 (Parasailing Boat)'), ('bike', 'Bike'), ('paint', 'Paint'), ('grass_cutter', 'Grass Cutter'), ('atv', 'ATV'), ('ambulance', 'Ambulance'), ('car', 'Car'), ('boat', 'Boat'), ('hiace', 'Hiace')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fuel Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='fueltransactionlog',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('engine_oil', 'Engine Oil')], max_length=10),
        ),
    ]
