# Generated by Django 5.2.7 on 2026-06-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_make_bullet_type_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ammotransactionlog",
            name="bullet_type",
        ),
        migrations.AlterField(
            model_name="ammotransactionlog",
            name="payment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid_via_cash", "Paid via Cash"),
                    ("paid_via_tickets", "Paid via Tickets"),
                    ("paid_via_groups", "Paid via Groups"),
                    ("free", "Free Bullets"),
                ],
                max_length=20,
            ),
        ),
    ]
