# Generated by Django 5.2.7 on 2026-06-12 19:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fuelentry_alter_fueltransactionlog_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmmoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bullet_type', models.CharField(choices=[('9mm', '9mm'), ('.45', '.45'), ('.22', '.22'), ('.38', '.38')], max_length=10)),
                ('bullet_status', models.CharField(choices=[('received', 'Received'), ('fired', 'Fired'), ('main_store', 'Main Store')], max_length=20)),
                ('bullet_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('payment', models.CharField(choices=[('paid_via_tickets', 'Paid via Tickets'), ('paid_via_groups', 'Paid via Groups'), ('free', 'Free Bullets')], max_length=20)),
                ('free_bullet_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ammo Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
