# Generated by Django 5.2.7 on 2026-06-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +92XXXXXXXXXX (e.g. +9230112345678)', max_length=15, null=True, unique=True),
        ),
    ]
