# Generated by Django 5.2.7 on 2025-10-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter your phone number (e.g. +923001234567)",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CASHIER", "Cashier"),
                    ("ACCOUNTANT", "Accountant"),
                    ("MAIN_CASHIER", "Main Cashier"),
                    ("CEO", "CEO"),
                    ("HOST", "Host"),
                    ("SALE", "Sale"),
                    ("CUSTOMER", "Customer"),
                    ("DRIVER", "Driver"),
                    ("WAITER", "Waiter"),
                    ("HR_MANAGER", "HR Manager"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
